### ISSUE TITLE
Allow for customizable error objects

### ISSUE THREAD

**Issue by Nickforall** [Nickforall/Freight#1]
Different applications have different needs, for now errors are a list of string, but I'm sure people want more customizable things in the future.

**Comment by gullitmiranda** [comment]
@Nickforall i wan't to try this lib, but the list of string is very limited to my need. 
How do you intend to enable this customization? 
For now I use `Kronky`, and I like how the ValidationMessage is build, but the construction of the payload sucks :/

**Comment by Nickforall** [comment]
First of all thank you for your interest in my library 😄 

Errors are no longer only a list of strings. It is the default option though.My documentation might be a bit unclear, so here is how you create a custom error object.

In your `config.exs`, you should add the following lines:
```elixir
config :freight,
  error_object: :user_error
```

The atom `:user_error` should be the name of the object you'd like to use for errors in the `errors` array of the given payload.

My error object in one of my projects looks like this:
```elixir
defmodule SketchqlWeb.Graphql.Types.Error do
  use Absinthe.Schema.Notation

  object :user_error do
    field(:message, type: non_null(:string))
    field(:code, type: :string)
  end
end
```

Then you can return a map in the error tuple returned by your resolvers:

```elixir
{:error, %{code: "unauthorized", message: "You are not authorized"}}
```

I'd recommend having a macro to generate those error maps, or having a set of predefined error map to return, because your resolvers can get messy with maps all over the place.

I hope this is clear, ping me if you have any more questions 😄 . I will make some time to improve this part of the documentation soon.

**Comment by gullitmiranda** [comment]
ye,I read the code, so I've got it.
however `Payload.build_payload/2` is restricted with `ErrorPayload.create_payload/1` of lib.
I know I can create my own `build_payload` and customize, but it's the best way?
